{"buggy_code": ["from horus.exceptions import (\n    AuthenticationException,\n    UserExistsException\n)\n\n\nclass AuthenticationService(object):\n    def __init__(self, backend):\n        self.backend = backend\n\n    def login(self, login, password):\n        \"\"\"\n        Authenticates the user by their login property and password.\n\n        Will raise an `AuthenticationException` if the username or password\n        are not found.\n        \"\"\"\n        #TODO: Check if the user is activated?\n        #TODO: Add a database log of authentication attempts\n        #TODO: Prevent multiple attempts from same IP\n        user = self.backend.get_user(login)\n\n        if (\n            user is None or\n            user.password != password\n        ):\n            raise AuthenticationException()\n\n        return user\n\n\nclass RegisterService(object):\n    def __init__(self, backend):\n        self.backend = backend\n\n    def create_user(self, login, password=None, email=None):\n        \"\"\"\n        Will create a user in the database\n        \"\"\"\n        user = self.backend.get_user(login)\n\n        if user is not None:\n            raise UserExistsException()\n\n        user = self.backend.create_user(\n            login,\n            password,\n            email\n        )\n\n        return user\n"], "fixing_code": ["from horus.exceptions import (\n    AuthenticationException,\n    UserExistsException\n)\n\n\ntry:\n    from hmac import compare_digest as is_equal\nexcept ImportError:\n    def is_equal(lhs, rhs):\n        \"\"\"Returns True if the two strings are equal, False otherwise.\n\n        The comparison is based on a common implementation found in Django.\n        This version avoids a short-circuit even for unequal lengths to reveal\n        as little as possible. It takes time proportional to the length of its\n        second argument.\n        \"\"\"\n        result = 0 if len(lhs) == len(rhs) else 1\n        lhs = lhs.ljust(len(rhs))\n        for x, y in zip(lhs, rhs):\n            result |= ord(x) ^ ord(y)\n        return result == 0\n\n\nclass AuthenticationService(object):\n    def __init__(self, backend):\n        self.backend = backend\n\n    def login(self, login, password):\n        \"\"\"\n        Authenticates the user by their login property and password.\n\n        Will raise an `AuthenticationException` if the username or password\n        are not found.\n        \"\"\"\n        #TODO: Check if the user is activated?\n        #TODO: Add a database log of authentication attempts\n        #TODO: Prevent multiple attempts from same IP\n        user = self.backend.get_user(login)\n\n        if (\n            user is None or\n            is_equal(user.password, password) is False\n        ):\n            raise AuthenticationException()\n\n        return user\n\n\nclass RegisterService(object):\n    def __init__(self, backend):\n        self.backend = backend\n\n    def create_user(self, login, password=None, email=None):\n        \"\"\"\n        Will create a user in the database\n        \"\"\"\n        user = self.backend.get_user(login)\n\n        if user is not None:\n            raise UserExistsException()\n\n        user = self.backend.create_user(\n            login,\n            password,\n            email\n        )\n\n        return user\n"], "filenames": ["horus/flows/local/services.py"], "buggy_code_start_loc": [4], "buggy_code_end_loc": [26], "fixing_code_start_loc": [5], "fixing_code_end_loc": [44], "type": "CWE-208", "message": "A vulnerability was found in Pylons horus and classified as problematic. Affected by this issue is some unknown functionality of the file horus/flows/local/services.py. The manipulation leads to observable timing discrepancy. The name of the patch is fd56ccb62ce3cbdab0484fe4f9c25c4eda6c57ec. It is recommended to apply a patch to fix this issue. VDB-217598 is the identifier assigned to this vulnerability.", "other": {"cve": {"id": "CVE-2014-125056", "sourceIdentifier": "cna@vuldb.com", "published": "2023-01-07T10:15:08.753", "lastModified": "2023-01-12T16:38:16.960", "vulnStatus": "Analyzed", "descriptions": [{"lang": "en", "value": "A vulnerability was found in Pylons horus and classified as problematic. Affected by this issue is some unknown functionality of the file horus/flows/local/services.py. The manipulation leads to observable timing discrepancy. The name of the patch is fd56ccb62ce3cbdab0484fe4f9c25c4eda6c57ec. It is recommended to apply a patch to fix this issue. VDB-217598 is the identifier assigned to this vulnerability."}], "metrics": {"cvssMetricV31": [{"source": "nvd@nist.gov", "type": "Primary", "cvssData": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "LOW", "integrityImpact": "NONE", "availabilityImpact": "NONE", "baseScore": 5.3, "baseSeverity": "MEDIUM"}, "exploitabilityScore": 3.9, "impactScore": 1.4}], "cvssMetricV30": [{"source": "cna@vuldb.com", "type": "Secondary", "cvssData": {"version": "3.0", "vectorString": "CVSS:3.0/AV:A/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N", "attackVector": "ADJACENT_NETWORK", "attackComplexity": "HIGH", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "LOW", "integrityImpact": "NONE", "availabilityImpact": "NONE", "baseScore": 2.6, "baseSeverity": "LOW"}, "exploitabilityScore": 1.2, "impactScore": 1.4}], "cvssMetricV2": [{"source": "cna@vuldb.com", "type": "Secondary", "cvssData": {"version": "2.0", "vectorString": "AV:A/AC:H/Au:S/C:P/I:N/A:N", "accessVector": "ADJACENT_NETWORK", "accessComplexity": "HIGH", "authentication": "SINGLE", "confidentialityImpact": "PARTIAL", "integrityImpact": "NONE", "availabilityImpact": "NONE", "baseScore": 1.4}, "baseSeverity": "LOW", "exploitabilityScore": 2.5, "impactScore": 2.9, "acInsufInfo": false, "obtainAllPrivilege": false, "obtainUserPrivilege": false, "obtainOtherPrivilege": false, "userInteractionRequired": false}]}, "weaknesses": [{"source": "cna@vuldb.com", "type": "Primary", "description": [{"lang": "en", "value": "CWE-208"}]}], "configurations": [{"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:a:pylonsproject:horus:*:*:*:*:*:pyramid:*:*", "versionEndExcluding": "2014-05-07", "matchCriteriaId": "372FD3F7-ACDE-4A93-98D6-6D2B9B1052C0"}]}]}], "references": [{"url": "https://github.com/Pylons/horus/commit/fd56ccb62ce3cbdab0484fe4f9c25c4eda6c57ec", "source": "cna@vuldb.com", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://vuldb.com/?ctiid.217598", "source": "cna@vuldb.com", "tags": ["Third Party Advisory", "VDB Entry"]}, {"url": "https://vuldb.com/?id.217598", "source": "cna@vuldb.com", "tags": ["Third Party Advisory", "VDB Entry"]}]}, "github_commit_url": "https://github.com/Pylons/horus/commit/fd56ccb62ce3cbdab0484fe4f9c25c4eda6c57ec"}}